"""anionpy.strings -- pure import surface for the `numpy.strings` block.

No logic lives here. See `anionpy/char.py`'s module docstring -- same rule,
same Rust-side symbols (`numpy.char.*` and `numpy.strings.*` are the same
underlying operation in real numpy 2.x for every name declared here).
"""

from anionpy._anionpy import (
    strings_add as add,
    strings_isalpha as isalpha,
    strings_isalnum as isalnum,
    strings_isdecimal as isdecimal,
    strings_isdigit as isdigit,
    strings_isnumeric as isnumeric,
    strings_isspace as isspace,
    strings_islower as islower,
    strings_isupper as isupper,
    strings_istitle as istitle,
    strings_str_len as str_len,
    strings_equal as equal,
    strings_not_equal as not_equal,
    strings_less as less,
    strings_less_equal as less_equal,
    strings_greater as greater,
    strings_greater_equal as greater_equal,
    strings_upper as upper,
    strings_lower as lower,
    strings_swapcase as swapcase,
    strings_title as title,
    strings_capitalize as capitalize,
    strings_strip as strip,
    strings_lstrip as lstrip,
    strings_rstrip as rstrip,
    strings_center as center,
    strings_ljust as ljust,
    strings_rjust as rjust,
    strings_zfill as zfill,
    strings_find as find,
    strings_rfind as rfind,
    strings_count as count,
    strings_startswith as startswith,
    strings_endswith as endswith,
    strings_index as index,
    strings_rindex as rindex,
    strings_replace as replace,
    strings_multiply as multiply,
    strings_encode as encode,
    strings_decode as decode,
    strings_partition as partition,
    strings_rpartition as rpartition,
)

__all__ = [
    "add",
    "isalpha",
    "isalnum",
    "isdecimal",
    "isdigit",
    "isnumeric",
    "isspace",
    "islower",
    "isupper",
    "istitle",
    "str_len",
    "equal",
    "not_equal",
    "less",
    "less_equal",
    "greater",
    "greater_equal",
    "upper",
    "lower",
    "swapcase",
    "title",
    "capitalize",
    "strip",
    "lstrip",
    "rstrip",
    "center",
    "ljust",
    "rjust",
    "zfill",
    "find",
    "rfind",
    "count",
    "startswith",
    "endswith",
    "index",
    "rindex",
    "replace",
    "multiply",
    "encode",
    "decode",
    "partition",
    "rpartition",
]
