[workspace]
resolver = "2"
members = [
    "ionp-core",
    "ionp-ion",
    "ionp-py",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
num-complex = "0.4.6"
num-traits = "0.2.19"
rayon = "1.12.0"
rustfft = "6.4.1"
faer = "0.24.4"
half = { version = "2.6.0", features = ["num-traits"] }
