"""anionpy.polynomial.laguerre.* differential registry entries.

NEW FILE (same pattern as legendre_cases.py/polynomial_cases.py/
linalg_cases.py): builds a `LAGUERRE_SPECS: dict[str, ItemSpec]` dict,
merged into `registry.REGISTRY` at the bottom of registry.py
(collision-checked, same pattern as every other `*_cases.py` merge).

Covers the same ~24 non-N-D items as legendre_cases.py's scope
(`Laguerre(ABCPolyBase)` and `*2d`/`*3d`/`*nd` composition items are NOT
covered, not attempted in this pass).

Laguerre looks like Legendre and is NOT -- this corpus is deliberately NOT
a relabeled copy of legendre_cases.py's case VALUES (though its structural
shape is intentionally identical, to keep the two bases easy to diff).
Specific divergences a naive copy-paste would miss, each pinned explicitly
below:
  - `lagline(off, scl)` returns `[off+scl, -scl]`, not `[off, scl]` --
    `legline_cases`' exact argument tuples would silently pass even with a
    swapped-in `legline` implementation if the EXPECTED values weren't
    independently generated by calling real numpy; since every case here
    is graded by calling `np.polynomial.laguerre.lagline` directly (no
    hardcoded expected arrays), this is caught structurally rather than by
    a hand-written assertion.
  - `lagcompanion`/`lagroots` have a `len(c) == 2` special case that
    returns `1 + c0/c1` (NOT Legendre's `-c0/c1`) -- this is the
    "degree-2 coefficient array" special case analogous to the
    herm2poly `n==2` bug the task brief warned about, and it is pinned
    EXPLICITLY below (not left to random sampling) as `degree1_pinned`
    (a length-2 coefficient array is polynomial degree 1, but it is the
    `len(c) == 2` BRANCH that is special-cased in the source, hence
    "degree1_pinned" names the polynomial degree while the comment calls
    out the branch condition precisely).
  - `laggauss` does NOT symmetrize (`x`/`w` are used exactly as the
    eigensolver + Newton polish produce them) and normalizes with
    `w /= w.sum()` -- NO leading factor of 2 (contrast Legendre's
    `w = w * (2.0 / w.sum())`).
  - `lagweight(x) = exp(-x)`, domain `[0, inf)` -- unlike `legweight`'s
    `x*0 + 1`, this is a real function of `x` and needs points that probe
    both the `[0, inf)` domain interior and negative/domain-violating `x`
    (numpy raises no domain error -- `exp(-x)` is defined everywhere;
    verified live: `NL.lagweight(-1.0)` returns `2.718281828459045`, no
    exception).
"""
from __future__ import annotations

import numpy as np

import anionpy as _anionpy

from registry import ItemSpec

# ---------------------------------------------------------------------------
# shared coefficient/point fixtures
# ---------------------------------------------------------------------------

INT_C = [1, 2, 3]
FLOAT_C = [1.0, 2.0, 3.0]
TRAILING_ZERO_C = [1.0, 2.0, 3.0, 0.0, 0.0]
ALL_ZERO_C = [0.0, 0.0, 0.0]
COMPLEX_C = [1 + 1j, 2 - 1j, 0.5j]
BOOL_C = [True, False, True]
SINGLE_C = [5.0]

C1 = [1.0, 2.0, 3.0]
C2 = [3.0, 2.0, 1.0]
C1_SHORT = [3.0, 2.0]

XS = [-2.0, -1.0, 0.0, 0.5, 1.0, 2.5]
X_SCALAR = 2.0
X_COMPLEX = 1 + 2j

# Laguerre's natural domain is [0, inf) -- fit/gauss fixtures probe that
# region specifically, in addition to the domain-agnostic XS used for
# val/der/int/vander (lagval etc. are defined for ANY x, real numpy raises
# no domain error outside [0, inf)).
XS_NONNEG = [0.0, 0.25, 1.0, 2.0, 5.0, 10.0]


def _std(pairs):
    return [(label, args, kwargs) for label, args, kwargs in pairs]


def _const_cases(attr):
    def gen():
        return [(f"{attr}_value", (), {})]
    return gen


# ---------------------------------------------------------------------------
# lagline / lagtrim
# ---------------------------------------------------------------------------

def lagline_cases():
    return _std([
        ("basic", (1.0, 2.0), {}),
        ("zero_scale", (3.0, 0.0), {}),
        ("negative", (-1.5, -2.5), {}),
        ("off_zero", (0.0, 4.0), {}),
        ("both_zero", (0.0, 0.0), {}),
    ])


def lagtrim_cases():
    return _std([
        ("trailing_zeros", (TRAILING_ZERO_C,), {}),
        ("all_zero", (ALL_ZERO_C,), {}),
        ("no_trim_needed", (FLOAT_C,), {}),
        ("with_tol", (list(TRAILING_ZERO_C) + [1e-10], 1e-8), {}),
        ("complex", (COMPLEX_C + [0j],), {}),
        ("int_input", (INT_C + [0],), {}),
        # as_series rejects bool outright -- same family as legtrim.
        ("bool_input", (BOOL_C,), {}),
    ])


# ---------------------------------------------------------------------------
# lagval
# ---------------------------------------------------------------------------

def lagval_cases():
    cases = []
    for c_label, c in [("int_c", INT_C), ("float_c", FLOAT_C), ("bool_c", BOOL_C),
                        ("complex_c", COMPLEX_C), ("trailing_zero_c", TRAILING_ZERO_C),
                        ("single_c", SINGLE_C)]:
        cases.append((f"scalar_x__{c_label}", (X_SCALAR, c), {}))
        cases.append((f"list_x__{c_label}", (XS, c), {}))
        cases.append((f"complex_x__{c_label}", (X_COMPLEX, c), {}))
    cases.append(("array_x_2d", (np.array([[0.0, 1.0], [2.0, 3.0]]), FLOAT_C), {}))
    # degree-2 coefficient array (len(c) == 3 hits the general Clenshaw
    # loop; len(c) == 2 hits the dedicated short-circuit branch
    # `c0=c[0]; c1=c[1]` inside lagval itself) -- pinned explicitly.
    cases.append(("len2_c_pinned", (XS, C1_SHORT), {}))
    cases.append(("len1_c_pinned", (XS, SINGLE_C), {}))
    # ---- Added 2026-08-07 (Monday): real-coefficient/complex-x regression
    # guard, multiple degrees. `lag_eval`'s Clenshaw recursion needed a
    # dedicated hybrid-typed kernel (`lag_eval_real_coef_complex_x` in
    # `ionp-core/src/laguerre.rs`) to match NumPy's "accumulator stays
    # real-typed until touched by the complex x" scalar semantics -- the
    # bug was invisible to the corpus above because none of its real-
    # coefficient cases have length >= 4 AND an evaluation point whose
    # divisor (3, 5, 6, ...) is not a power of 2 (`complex_div`'s Smith's-
    # algorithm real/real path only disagrees with plain division on
    # non-power-of-2 divisors -- measured directly, ~33% mismatch on 3/5/6
    # vs. 0% on 2/4). These four pin exactly that combination, real
    # coefficients of length 4-7 (so the loop passes through divisors
    # 3, 4, 5, 6) at a non-"nice" complex x.
    _real_x_complex = 0.9505 - 1.3820j
    cases.append(("real_c_len4_complex_x_DEGREE_REGRESSION",
                   (_real_x_complex, [0.5993, -1.21, 2.07, 0.44]), {}))
    cases.append(("real_c_len5_complex_x_DEGREE_REGRESSION",
                   (_real_x_complex, [0.5993, -1.21, 2.07, 0.44, -0.83]), {}))
    cases.append(("real_c_len6_complex_x_DEGREE_REGRESSION",
                   (_real_x_complex, [0.5993, -1.21, 2.07, 0.44, -0.83, 1.6]), {}))
    cases.append(("real_c_len7_complex_x_DEGREE_REGRESSION",
                   (_real_x_complex, [0.5993, -1.21, 2.07, 0.44, -0.83, 1.6, -2.05]), {}))
    return cases


# ---------------------------------------------------------------------------
# add / sub / mulx / mul / div / pow
# ---------------------------------------------------------------------------

def lagadd_cases():
    return _std([
        ("same_len", (C1, C2), {}),
        ("c1_shorter", (C1_SHORT, C1), {}),
        ("c2_shorter", (C1, C1_SHORT), {}),
        ("int_plus_float", (INT_C, FLOAT_C), {}),
        ("bool_plus_int", (BOOL_C, INT_C), {}),
        ("complex_plus_real", (COMPLEX_C, FLOAT_C), {}),
        ("cancels_to_zero", ([1.0, 2.0], [-1.0, -2.0]), {}),
        ("trailing_zero_result", ([1.0, 2.0, 3.0], [0.0, 0.0, -3.0]), {}),
    ])


def lagsub_cases():
    return _std([
        ("same_len", (C1, C2), {}),
        ("c1_shorter", (C1_SHORT, C1), {}),
        ("identical_cancels", (FLOAT_C, FLOAT_C), {}),
        ("complex_minus_real", (COMPLEX_C, FLOAT_C), {}),
        ("int_minus_bool", (INT_C, BOOL_C), {}),
    ])


def lagmulx_cases():
    return _std([
        ("float_c", (FLOAT_C,), {}),
        ("int_c", (INT_C,), {}),
        ("zero_series", (ALL_ZERO_C[:1],), {}),  # numpy special-cases [0]
        ("complex_c", (COMPLEX_C,), {}),
        ("single_nonzero", (SINGLE_C,), {}),
        ("bool_c", (BOOL_C,), {}),  # as_series-family: rejects bool
        # ---- Added 2026-08-08 (Monday), ticket #84 ----
        # Same defect class and fix as legmulx's analogous cases in
        # legendre_cases.py (missing `pu.as_series` pre-trim before the
        # `len(c)==1 && c[0]==0` zero-series fast-path check, lost
        # shape/sign on all-underflow input). Fixed in
        # `ionp-core/src/laguerre.rs`. Permanent regression guard.
        ("negative_both_first_coef", ([-4.5 - 2.5j],), {}),
    ])


def lagmul_cases():
    return _std([
        ("basic", (C1, C2), {}),
        ("int_times_float", (INT_C, FLOAT_C), {}),
        ("complex_times_real", (COMPLEX_C, FLOAT_C), {}),
        ("with_zero_series", (FLOAT_C, ALL_ZERO_C[:1]), {}),
        ("trailing_zero_operand", (TRAILING_ZERO_C, C2), {}),
        ("single_by_single", ([2.0], [3.0]), {}),
        ("bool_operand", (BOOL_C, FLOAT_C), {}),  # as_series-family: rejects bool
        # len(c) == 2 special-cased branch, and the 4+-term general loop
        # that exercises the (2*nd-1)*c1 - mulx(c1), THEN divide grouping.
        ("len2_operand", (C1_SHORT, C2), {}),
        ("four_term", ([1.0, 2.0, 3.0, 4.0], [1.0, -1.0, 2.0, -2.0]), {}),
        # ---- Added 2026-08-08 (Monday), ticket #84 ----
        # Ticket #84's own repro (adapted to laguerre): underflow/
        # subnormal, all-signed-zero-producing inputs. Root cause and
        # fix identical to legmul's analogous case above (missing
        # `as_series` pre-trim before `pad_add`/`pad_sub` in `lagmul`'s
        # internal recursion, fixed in `ionp-core/src/laguerre.rs`).
        # Permanent regression guard.
        ("underflow_signed_zero_ticket84",
         ([5e-324, 5e-324, 5e-324], [-5e-324, -5e-324]), {}),
    ])


def lagdiv_cases():
    return _std([
        ("basic", (C1, C2), {}),
        ("swap", (C2, C1), {}),
        ("c1_shorter_than_c2", (C1_SHORT, C1), {}),
        ("divide_by_scalar", (C1, [2.0]), {}),
        ("exact_division", ([2.0, 4.0, 6.0], [1.0, 2.0]), {}),
        ("complex", (COMPLEX_C, [1.0, 1.0]), {}),
        ("divide_by_zero_series", (C1, [0.0]), {}),
        ("bool_c1", (BOOL_C, [1.0, 2.0]), {}),  # as_series-family: rejects bool
        # ---- Ticket #87 (2026-08-10, Monday): `lagdiv` never did numpy
        # `_div`'s top-level `[c1, c2] = as_series([c1, c2])` pre-trim, so an
        # untrimmed trailing exact zero in `c1` leaked through into the
        # returned quotient/remainder as a SHAPE divergence (numpy trims
        # `c1` to length 3 before the `lc1 < lc2` check ever runs; pre-fix
        # anionpy used the untrimmed length-5 `c1_in`, returning the wrong
        # remainder shape). Repro measured directly from an out-of-corpus
        # diversity sweep (seed 0xC0FFEE), not the ticket's own probe.
        ("untrimmed_trailing_zero_c1_ticket87",
         ([-0.32019105, 1.45823375, -0.86985882, 0.0, 0.0], [1.67652212]), {}),
        # A SECOND case exercising the same missing pre-trim on `c2`
        # instead: a trailing exact zero on the DIVISOR made anionpy's
        # untrimmed `c2.last() == 0` check false-positive a ZeroDivisionError
        # numpy never raises (numpy trims `c2` first, sees a genuine nonzero
        # last coefficient, and divides normally).
        ("untrimmed_trailing_zero_c2_ticket87",
         ([0.42691841, 0.212777, -0.02226693, 0.61897555, 0.0, 0.0],
          [-0.07402421, 0.23126075, 0.0]), {}),
    ])


def lagpow_cases():
    return _std([
        ("square", (C1, 2), {}),
        ("cube", (FLOAT_C, 3), {}),
        # power_zero is dtype-PRESERVING for lagpow, same as legpow --
        # verified live: L.lagpow([1j, 2j], 0) -> array([1.+0.j]) complex128.
        ("power_zero", (C1, 0), {}),
        ("power_zero_complex", (COMPLEX_C, 0), {}),
        ("power_one", (C1, 1), {}),
        ("complex_base", (COMPLEX_C, 2), {}),
        ("int_c", (INT_C, 2), {}),
    ])


# ---------------------------------------------------------------------------
# der / int
# ---------------------------------------------------------------------------

def lagder_cases():
    C = [1.0, 2.0, 3.0, 4.0]
    return _std([
        ("first_order", (C, 1), {}),
        ("third_order", (C, 3), {}),
        ("zero_order", (C, 0), {}),
        ("order_exceeds_degree", (C, 10), {}),
        ("with_scale", (C, 1, 2.0), {}),
        ("complex_c", (COMPLEX_C, 1), {}),
        ("int_c", (INT_C, 1), {}),
        # lagder does its OWN dtype handling, NOT `as_series` -- bool
        # promoted, never rejected. Verified:
        # L.lagder([True, False, True], 1) -> array([1., -1.]), no error.
        ("bool_c", (BOOL_C, 1), {}),
    ])


def lagint_cases():
    C = [1.0, 2.0, 3.0]
    return _std([
        ("first_order_default_k", (C, 1), {}),
        ("with_k", (C, 1, [1.0]), {}),
        ("second_order_with_k", (C, 2, [1.0, 2.0]), {}),
        ("with_lbnd", (C, 1, [0.0], 1.0), {}),
        ("with_scale", (C, 1, [0.0], 0.0, 2.0), {}),
        ("complex_c", (COMPLEX_C, 1, [0.0]), {}),
        ("int_c", (INT_C, 1, [0.0]), {}),
        ("bool_c", (BOOL_C, 1, [0.0]), {}),  # own-dtype path: bool promoted, not rejected
    ])


# ---------------------------------------------------------------------------
# vander / companion
# ---------------------------------------------------------------------------

def lagvander_cases():
    return _std([
        ("basic", (XS, 5), {}),
        ("deg_zero", (XS, 0), {}),
        ("deg_one_pinned", (XS, 1), {}),  # v[1] = 1 - x, not x -- pinned explicitly
        ("scalar_x", (X_SCALAR, 3), {}),
        ("complex_x", ([1 + 1j, 2 - 1j, 0.5j], 4), {}),
        ("int_x", ([1, 2, 3], 3), {}),
        ("bool_x", ([True, False], 2), {}),  # own-dtype path: bool promoted, not rejected
        ("nonneg_x", (XS_NONNEG, 6), {}),
    ])


def lagcompanion_cases():
    return _std([
        ("degree2", (C1,), {}),
        # len(c) == 2 special case: [[1 + c0/c1]] -- pinned explicitly,
        # analogous to the herm2poly n==2 bug the task brief warned about.
        # NOT Legendre's [-c0/c1] shape.
        ("degree1_pinned_len2branch", (C1_SHORT,), {}),
        ("degree4", ([1.0, 0.0, -2.0, 0.0, 1.0],), {}),
        ("complex", (COMPLEX_C,), {}),
        ("int_c", (INT_C,), {}),
        ("bool_c", (BOOL_C,), {}),  # as_series-family: rejects bool
    ])


# ---------------------------------------------------------------------------
# fromroots / roots
# ---------------------------------------------------------------------------

def lagfromroots_cases():
    return _std([
        ("real_roots", ([-1.0, 0.0, 1.0],), {}),
        ("no_roots", ([],), {}),
        ("single_root", ([3.0],), {}),
        ("complex_roots", ([-1j, 0.0, 1j],), {}),
        ("repeated_root", ([1.0, 1.0, -1.0],), {}),
        ("five_roots", ([-2.0, -1.0, 0.0, 1.0, 2.0],), {}),
        ("bool_roots", ([True, False],), {}),  # as_series-family: rejects bool
        # ---- Added 2026-08-08 (Monday), ticket #84 ----
        # KNOWN FAILURE, added deliberately as a documented, permanent
        # regression case -- NOT to be treated as a build-breaker.
        # `polynomial.laguerre.lagfromroots` was REVOKED from "exact" in
        # `anionpy/_state/polynomial.py` this ticket: the single-root
        # path (`cnt == 1`, no pairwise `lagmul` reduction) builds
        # `off = complex(-complex(r))` as a native Python `complex`,
        # then `lagline(off, 1)` computes `off + 1` via CPython's
        # real-plus-complex special-cased addition, which does NOT
        # perform a genuine IEEE add on the imaginary component -- it
        # leaves `off.imag`'s sign bit bit-for-bit unchanged, whereas
        # real numpy's `off` is a genuine `np.complex128` scalar and
        # `off + scl` goes through numpy's own scalar-add ufunc (a real
        # componentwise IEEE add). Only triggers for COMPLEX-typed
        # single-root input (the pre-existing `single_root` case above
        # uses a real float and does NOT trigger it -- verified: real
        # input routes through `-float(rl[i])`, never touching the
        # native-`complex` addition path at all). Root cause lives in
        # `anionpy/polynomial/laguerre.py` (`lagfromroots`/`lagline`),
        # OUTSIDE this ticket's edit scope (ionp-core/ionp-py/state
        # file/differential tests only) -- left for a follow-up ticket.
        # This case is EXPECTED to report verdict='fail' in run.py's
        # output; see KNOWN-DIFFERENCES.md for the tracked entry.
        ("single_root_complex_ticket84", ([3.0 + 0j],), {}),
    ])


def lagroots_cases():
    return _std([
        ("real_roots", (np.polynomial.laguerre.lagfromroots([-1.0, 0.0, 1.0]),), {}),
        ("complex_roots", (np.polynomial.laguerre.lagfromroots([-1j, 0.0, 1j]),), {}),
        # len(c) == 2 special case: 1 + c0/c1 -- pinned explicitly, this is
        # the "degree exactly 2 [coefficient array]" pin the task brief
        # requires, mirroring lagcompanion_cases' degree1_pinned_len2branch.
        ("degree1_pinned_len2branch", (C1_SHORT,), {}),
        ("degree0_no_roots", (SINGLE_C,), {}),
        ("five_real_roots", (np.polynomial.laguerre.lagfromroots(
            [-2.0, -1.0, 0.0, 1.0, 2.0]),), {}),
    ])


def _canonical_root_order(arr):
    """See legendre_cases.py's `_canonical_root_order` -- identical
    stabilization strategy (round the sort KEY, not the compared values,
    to 6 decimals -- three orders of magnitude coarser than
    LAGROOTS_COMPLEX_EPS below), used here for the SAME reason: two
    independent eigensolvers landing on differently-signed near-zero roots
    must not spuriously fail on ordering alone. `lagroots`'s output dtype
    also depends on `_to_real_if_imag_zero`-equivalent downcasting (see
    anionpy/polynomial/laguerre.py's `lagroots`), so `arr` may be real or
    complex depending on the case; `.real`/`.imag` both work on a real
    float64 array (imag is all zero) so this helper is dtype-agnostic."""
    arr = np.asarray(arr)
    key = list(zip(np.round(arr.real, 6), np.round(np.imag(arr), 6)))
    order = sorted(range(len(arr)), key=lambda i: key[i])
    return arr[order]


def _lagroots_numpy_sorted(c):
    return _canonical_root_order(np.polynomial.laguerre.lagroots(c))


def _lagroots_ionp_sorted(c):
    import anionpy as ap
    r = ap.polynomial.laguerre.lagroots(ap.array(c))
    r_np = np.asarray(r.tolist() if hasattr(r, "tolist") else r)
    return _canonical_root_order(r_np)


# ---------------------------------------------------------------------------
# fit
# ---------------------------------------------------------------------------

def lagfit_cases():
    rng = np.random.default_rng(20260807)
    x = np.array(XS_NONNEG + [3.0, 4.0, 6.0, 7.0, 8.0, 0.5, 1.5, 2.5, 3.5,
                               4.5, 5.5, 6.5, 7.5, 8.5, 9.0, 9.5, 0.1, 0.2,
                               0.3, 0.75, 1.25])
    y = np.polynomial.laguerre.lagval(x, [0.0, 1.0, 0.0, -1.0])
    y_noisy = y + rng.normal(scale=0.01, size=x.shape)
    y2d = np.stack([y, x**2], axis=1)
    return _std([
        ("cubic_exact", (x, y, 3), {}),
        ("cubic_noisy", (x, y_noisy, 3), {}),
        ("linear_underfit", (x, y, 1), {}),
        ("y_2d", (x, y2d, 3), {}),
        ("small_n", ([1.0, 2.0, 3.0, 4.0], [1.0, 4.0, 9.0, 16.0], 2), {}),
    ])


# ---------------------------------------------------------------------------
# laggauss / lagweight
# ---------------------------------------------------------------------------

def laggauss_cases():
    return _std([
        ("deg1", (1,), {}),
        ("deg2", (2,), {}),
        ("deg5", (5,), {}),
        ("deg10", (10,), {}),
        ("deg25", (25,), {}),
    ])


def lagweight_cases():
    return _std([
        ("scalar", (0.5,), {}),
        ("list", (XS,), {}),
        ("array", (np.array(XS),), {}),
        ("nonneg", (XS_NONNEG,), {}),
    ])


# ---------------------------------------------------------------------------
# lag2poly / poly2lag
# ---------------------------------------------------------------------------

def lag2poly_cases():
    return _std([
        ("float_c", (FLOAT_C,), {}),
        ("int_c", (INT_C,), {}),
        ("complex_c", (COMPLEX_C,), {}),
        ("trailing_zero_c", (TRAILING_ZERO_C,), {}),
        ("single_c", (SINGLE_C,), {}),
        ("two_term", (C1_SHORT,), {}),
        ("bool_c", (BOOL_C,), {}),  # as_series-family: rejects bool
    ])


def poly2lag_cases():
    return _std([
        ("float_c", (FLOAT_C,), {}),
        ("int_c", (INT_C,), {}),
        ("complex_c", (COMPLEX_C,), {}),
        ("trailing_zero_c", (TRAILING_ZERO_C,), {}),
        ("single_c", (SINGLE_C,), {}),
        ("bool_c", (BOOL_C,), {}),  # as_series-family: rejects bool
    ])


# Measured 2026-08-07 via /private/tmp/lag_eps_sweep.py, run OUT of this
# corpus (independent seeded sweeps, 20,000 samples each -- the
# MIN_ULP_SWEEP_N floor `ItemSpec.__post_init__` enforces on every
# epsilon_tolerance below). These are Laguerre's OWN measured constants,
# NOT inherited from LEGFIT_EPS/LEGROOTS_COMPLEX_EPS/LEGGAUSS_EPS in
# legendre_cases.py -- filled in by the measurement pass after this corpus
# file is written and the Rust implementation exists to sweep against.
LAGFIT_EPS = 6.404363387358187e-11
LAGROOTS_COMPLEX_EPS = 1.0527126332426917e-05
LAGGAUSS_EPS = 4.746203430272544e-15


# ---------------------------------------------------------------------------
# Task #34 (2026-08-08): lagval2d/lagval3d/lagvalnd/laggrid2d/laggrid3d/
# lagvander2d/lagvander3d -- built on polyutils.py's shared _valnd/_gridnd/
# _vander_nd/_vander_nd_flat machinery (see that module's docstring for the
# ticket-premise correction: FOUR shared helpers back this family, not the
# two -- _vander_nd/_vander_nd_flat -- the ticket named). Corpus varies
# point count (1-4 per axis), degree (0-2 per axis), and dtype (float64,
# complex128, int -- promoted via _common_dtype). float16/float32/
# complex64 are DELIBERATELY EXCLUDED: the already-declared, already-
# shipped 1-D `lagval`/`lagvander` kernels this family is built on
# universally upcast those three dtypes to float64/complex128 (values
# match real numpy bit-exact, but dtype does not) -- a pre-existing
# divergence in code this ticket did not write and has no permission to
# touch (lives in the shared Rust kernels, confirmed present for all six
# bases, not introduced here). See docs/TICKET-34-*.md.

def _lag_nd_base_cases():
    rng = np.random.default_rng(20260808)

    def mk(n, dx, dy, dz, dtype_label):
        if dtype_label == "int":
            xs = rng.integers(-4, 4, n).astype(np.int64)
            ys = rng.integers(-4, 4, n).astype(np.int64)
            zs = rng.integers(-4, 4, n).astype(np.int64)
            c2 = rng.integers(-4, 4, (dx + 1, dy + 1)).astype(np.int64)
            c3 = rng.integers(-4, 4, (dx + 1, dy + 1, dz + 1)).astype(np.int64)
        elif dtype_label == "complex128":
            xs = rng.standard_normal(n) + 1j * rng.standard_normal(n)
            ys = rng.standard_normal(n) + 1j * rng.standard_normal(n)
            zs = rng.standard_normal(n) + 1j * rng.standard_normal(n)
            c2 = rng.standard_normal((dx + 1, dy + 1)) + 1j * rng.standard_normal((dx + 1, dy + 1))
            c3 = rng.standard_normal((dx + 1, dy + 1, dz + 1)) + 1j * rng.standard_normal((dx + 1, dy + 1, dz + 1))
        else:
            xs = rng.standard_normal(n)
            ys = rng.standard_normal(n)
            zs = rng.standard_normal(n)
            c2 = rng.standard_normal((dx + 1, dy + 1))
            c3 = rng.standard_normal((dx + 1, dy + 1, dz + 1))
        return xs.tolist(), ys.tolist(), zs.tolist(), c2.tolist(), c3.tolist(), [dx, dy, dz]

    cases = [
        ("single_point_degree_one", *mk(1, 1, 1, 1, "float64")),
        ("degree_zero_all_axes", *mk(2, 0, 0, 0, "float64")),
        ("complex_points_and_coefs", *mk(3, 1, 1, 1, "complex128")),
        ("int_points_and_coefs", *mk(3, 2, 1, 1, "int")),
    ]
    for dtype_label in ("float64", "complex128", "int"):
        for i in range(25):
            n = int(rng.integers(1, 5))
            dx, dy, dz = (int(rng.integers(0, 3)) for _ in range(3))
            cases.append((f"adversarial_{dtype_label}_{i}", *mk(n, dx, dy, dz, dtype_label)))
    return cases


def lagval2d_cases():
    return [(lbl, (xs, ys, c2), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


def lagval3d_cases():
    return [(lbl, (xs, ys, zs, c3), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


def lagvalnd_cases():
    return [(lbl, ((xs, ys, zs), c3), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


def laggrid2d_cases():
    return [(lbl, (xs, ys, c2), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


def laggrid3d_cases():
    return [(lbl, (xs, ys, zs, c3), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


def lagvander2d_cases():
    return [(lbl, (xs, ys, deg[:2]), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


def lagvander3d_cases():
    return [(lbl, (xs, ys, zs, deg), {}) for lbl, xs, ys, zs, c2, c3, deg in _lag_nd_base_cases()]


# ---------------------------------------------------------------------------
# assembling the spec dict
# ---------------------------------------------------------------------------

def _build_laguerre_specs() -> dict[str, ItemSpec]:
    specs: dict[str, ItemSpec] = {}

    specs["polynomial.laguerre.lagdomain"] = ItemSpec(
        name="polynomial.laguerre.lagdomain", kind="custom",
        custom_cases=_const_cases("lagdomain"),
        numpy_adapter=lambda: np.polynomial.laguerre.lagdomain,
        ionp_adapter=lambda: __import__("anionpy").polynomial.laguerre.lagdomain,
        atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagzero"] = ItemSpec(
        name="polynomial.laguerre.lagzero", kind="custom",
        custom_cases=_const_cases("lagzero"),
        numpy_adapter=lambda: np.polynomial.laguerre.lagzero,
        ionp_adapter=lambda: __import__("anionpy").polynomial.laguerre.lagzero,
        atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagone"] = ItemSpec(
        name="polynomial.laguerre.lagone", kind="custom",
        custom_cases=_const_cases("lagone"),
        numpy_adapter=lambda: np.polynomial.laguerre.lagone,
        ionp_adapter=lambda: __import__("anionpy").polynomial.laguerre.lagone,
        atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagx"] = ItemSpec(
        name="polynomial.laguerre.lagx", kind="custom",
        custom_cases=_const_cases("lagx"),
        numpy_adapter=lambda: np.polynomial.laguerre.lagx,
        ionp_adapter=lambda: __import__("anionpy").polynomial.laguerre.lagx,
        atol=0.0, rtol=0.0,
    )

    specs["polynomial.laguerre.lagline"] = ItemSpec(
        name="polynomial.laguerre.lagline", kind="custom",
        custom_cases=lagline_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagtrim"] = ItemSpec(
        name="polynomial.laguerre.lagtrim", kind="custom",
        custom_cases=lagtrim_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagval"] = ItemSpec(
        name="polynomial.laguerre.lagval", kind="custom",
        custom_cases=lagval_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagadd"] = ItemSpec(
        name="polynomial.laguerre.lagadd", kind="custom",
        custom_cases=lagadd_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagsub"] = ItemSpec(
        name="polynomial.laguerre.lagsub", kind="custom",
        custom_cases=lagsub_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagmulx"] = ItemSpec(
        name="polynomial.laguerre.lagmulx", kind="custom",
        custom_cases=lagmulx_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagmul"] = ItemSpec(
        name="polynomial.laguerre.lagmul", kind="custom",
        custom_cases=lagmul_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagdiv"] = ItemSpec(
        name="polynomial.laguerre.lagdiv", kind="custom",
        custom_cases=lagdiv_cases, atol=0.0, rtol=0.0, multi_output=True,
    )
    specs["polynomial.laguerre.lagpow"] = ItemSpec(
        name="polynomial.laguerre.lagpow", kind="custom",
        custom_cases=lagpow_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagder"] = ItemSpec(
        name="polynomial.laguerre.lagder", kind="custom",
        custom_cases=lagder_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagint"] = ItemSpec(
        name="polynomial.laguerre.lagint", kind="custom",
        custom_cases=lagint_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagvander"] = ItemSpec(
        name="polynomial.laguerre.lagvander", kind="custom",
        custom_cases=lagvander_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagcompanion"] = ItemSpec(
        name="polynomial.laguerre.lagcompanion", kind="custom",
        custom_cases=lagcompanion_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagfromroots"] = ItemSpec(
        name="polynomial.laguerre.lagfromroots", kind="custom",
        custom_cases=lagfromroots_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lagroots"] = ItemSpec(
        name="polynomial.laguerre.lagroots", kind="custom",
        custom_cases=lagroots_cases, atol=0.0, rtol=0.0,
        numpy_adapter=_lagroots_numpy_sorted,
        ionp_adapter=_lagroots_ionp_sorted,
        epsilon_tolerance={
            "complex128": ("abs", LAGROOTS_COMPLEX_EPS),
            "float64": ("abs", LAGROOTS_COMPLEX_EPS),
        },
        epsilon_tolerance_justification=(
            "lagroots = lagcompanion (exact) + linalg.eigvals (independent "
            "eigensolver call path vs real numpy's LAPACK dgeev, "
            "non-bit-identical by construction) + a "
            "_to_real_if_imag_zero-equivalent real-downcast step (unlike "
            "legroots, lagroots DOES cast to real when every eigenvalue's "
            "imaginary part is exactly 0.0 AND the companion matrix's "
            "dtype was real -- verified directly against "
            "numpy/polynomial/laguerre.py) + sort (see numpy_adapter/ "
            "ionp_adapter above -- lagroots makes no ordering guarantee). "
            "Bound is the max abs coordinate error over two independent "
            "20,000-sample seeded sweeps (degree 1-7 real-rooted "
            "polynomials, and even-degree exact-conjugate-pair complex-"
            "rooted polynomials -- both canonically re-sorted before "
            "comparison via the same rounded-key strategy as "
            "numpy_adapter/ionp_adapter above, since a plain real-part "
            "sort can itself mis-pair near-tied conjugate roots and "
            "manufacture a spurious multi-unit error that is really just "
            "an ordering artifact), independent of lagroots_cases() above "
            "-- see /private/tmp/lag_eps_sweep.py. (The real-rooted sweep "
            "measured the larger of the two maxima, 1.05e-05 vs 1.02e-08 "
            "for the complex sweep; one shared bound is used for both "
            "dtype keys, matching legendre_cases.py's precedent.)"
        ),
        epsilon_sweep={
            "complex128": (20000, LAGROOTS_COMPLEX_EPS),
            "float64": (20000, LAGROOTS_COMPLEX_EPS),
        },
    )
    specs["polynomial.laguerre.lagfit"] = ItemSpec(
        name="polynomial.laguerre.lagfit", kind="custom",
        custom_cases=lagfit_cases,
        atol=0.0, rtol=0.0,
        epsilon_tolerance={"float64": ("rel", LAGFIT_EPS)},
        epsilon_tolerance_justification=(
            "Least-squares fit: normalized-Vandermonde build (exact, Rust) "
            "+ linalg.lstsq (independent SVD call path vs real numpy, not "
            "bit-identical) + un-normalize. Bound is the max relative "
            "coefficient disagreement over a 20,000-fit seeded sweep on "
            "the [0, inf) domain, independent of lagfit_cases() -- see "
            "/private/tmp/lag_eps_sweep.py."
        ),
        epsilon_sweep={"float64": (20000, LAGFIT_EPS)},
    )
    specs["polynomial.laguerre.laggauss"] = ItemSpec(
        name="polynomial.laguerre.laggauss", kind="custom",
        custom_cases=laggauss_cases,
        atol=0.0, rtol=0.0, multi_output=True,
        epsilon_tolerance={"float64": ("abs", LAGGAUSS_EPS)},
        epsilon_tolerance_justification=(
            "laggauss's nodes come from linalg.eigvalsh on the (symmetric, "
            "for a pure top-degree companion) companion matrix (independent "
            "symmetric-eigensolver call path vs real numpy's LAPACK "
            "dsyevd, not bit-identical) followed by one Newton polish step "
            "and a weight computation built from lagval/lagder -- all exact "
            "Rust arithmetic once the eigenvalues differ in their last bit "
            "or two. Bound is the max abs coordinate error (over both "
            "nodes x and weights w) across a 20,000-sample seeded sweep of "
            "degrees 1-59, independent of laggauss_cases() above -- see "
            "/private/tmp/lag_eps_sweep.py."
        ),
        epsilon_sweep={"float64": (20000, LAGGAUSS_EPS)},
    )
    specs["polynomial.laguerre.lagweight"] = ItemSpec(
        name="polynomial.laguerre.lagweight", kind="custom",
        custom_cases=lagweight_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.lag2poly"] = ItemSpec(
        name="polynomial.laguerre.lag2poly", kind="custom",
        custom_cases=lag2poly_cases, atol=0.0, rtol=0.0,
    )
    specs["polynomial.laguerre.poly2lag"] = ItemSpec(
        name="polynomial.laguerre.poly2lag", kind="custom",
        custom_cases=poly2lag_cases, atol=0.0, rtol=0.0,
    )

    # -- Task #34 (2026-08-08): *val2d/*val3d/*valnd/*grid2d/*grid3d/
    # *vander2d/*vander3d, see this file's comment block above the
    # generators for corpus design and the float16/32/complex64 exclusion.
    for _fn in ("lagval2d", "lagval3d", "lagvalnd", "laggrid2d",
                "laggrid3d", "lagvander2d", "lagvander3d"):
        specs[f"polynomial.laguerre.{_fn}"] = ItemSpec(
            name=f"polynomial.laguerre.{_fn}", kind="custom",
            custom_cases=globals()[f"{_fn}_cases"], atol=0.0, rtol=0.0,
        )
    del _fn

    return specs


LAGUERRE_SPECS = _build_laguerre_specs()
