"""anionpy.ma -- pure import surface for the `numpy.ma` (masked array) block.

SCOPE (see /Users/rabite/Monday/ionp/MA-DESIGN.md): this module implements
Phases 0-2 only:

  Phase 0: the `MaskedArray` core type itself, the `nomask` singleton (with
           identity semantics distinct from a plain `False`/all-False mask
           array), the `masked`/`masked_singleton` constant, and the
           `getdata`/`getmask`/`getmaskarray`/`filled` plumbing functions.
  Phase 1: ~31 items that collapse into the generic `_MaskedUnaryOperation`
           / `_MaskedBinaryOperation` wrapper families over an
           already-declared-exact anionpy base function.
  Phase 2: ~12 items whose non-masked anionpy counterpart is already declared
           exact (the `_like` family, plain creation, shape-transforming
           ops, `copy`, and the mask-ignoring `size`/`ndim`/`shape`
           delegators).

Mask construction helpers (`masked_where` and friends), the fill-value
machinery beyond a hardcoded default table, contiguity utilities, and the
handful of mutating methods are Phases 3-6 and are explicitly OUT OF SCOPE
for this module -- they are simply not defined here, not stubbed.

No logic beyond attribute/dispatch plumbing lives here or in `core.py`:
every actual number is produced by an already-Rust-backed anionpy function.
See `core.py`'s module docstring and each wrapper factory for exactly which
Rust-backed call does the work.
"""

from anionpy.ma.core import (
    MaskedArray,
    MaskedConstant,
    nomask,
    masked,
    masked_singleton,
    getdata,
    getmask,
    getmaskarray,
    filled,
    # Phase 1: unary pass-through family
    abs,
    absolute,
    fabs,
    exp,
    sin,
    sinh,
    cosh,
    arctan,
    arcsinh,
    negative,
    conjugate,
    ceil,
    floor,
    logical_not,
    # Phase 1: binary mask-combine family
    add,
    subtract,
    multiply,
    bitwise_and,
    bitwise_or,
    bitwise_xor,
    arctan2,
    logical_and,
    logical_or,
    logical_xor,
    # Phase 2
    zeros_like,
    ones_like,
    empty_like,
    zeros,
    ones,
    empty,
    identity,
    repeat,
    take,
    copy,
    size,
    ndim,
    shape,
    # Phase 3: mask construction / testers
    MaskType,
    bool_,
    MAError,
    MaskError,
    is_mask,
    is_masked,
    isMaskedArray,
    isMA,
    isarray,
    make_mask,
    make_mask_none,
    mask_or,
    masked_where,
    masked_equal,
    masked_not_equal,
    masked_greater,
    masked_greater_equal,
    masked_less,
    masked_less_equal,
    masked_inside,
    masked_outside,
    masked_invalid,
    masked_values,
    masked_object,
    masked_array,
    masked_all,
    masked_all_like,
    masked_print_option,
    # Phase 4: fill-value machinery
    default_fill_value,
    minimum_fill_value,
    maximum_fill_value,
    common_fill_value,
    set_fill_value,
    fix_invalid,
    # Phase 5: contiguity / structure / joining
    vstack,
    hstack,
    dstack,
    column_stack,
    row_stack,
    append,
    diagflat,
    transpose,
    swapaxes,
    reshape,
    ravel,
    squeeze,
    expand_dims,
    atleast_1d,
    atleast_2d,
    atleast_3d,
    resize,
    compress,
    compressed,
    nonzero,
    # Phase 6: domained unary/binary families
    sqrt,
    log,
    log2,
    log10,
    arcsin,
    arccos,
    arccosh,
    arctanh,
    divide,
    true_divide,
    floor_divide,
    remainder,
    mod,
    fmod,
    # Phase 7: reductions. `mean` is deliberately NOT exported -- see the
    # float16 defect documented in anionpy/_state/ma.py. Exporting it would
    # make a known-divergent item reachable under a numpy-compatible name.
    count,
    sum,
    any,
    all,
    min,
    max,
    # Phase 8: comparison family, a few `_frommethod`-style aliases, and
    # independent reduction-shaped functions. `left_shift`/`right_shift`,
    # `allclose`, `diag`/`diagonal`, `atleast_1d`/`2d`/`3d`, `concatenate`,
    # `clip`, `round`/`around`, `choose`, `arange`, `array`, `prod`/
    # `product` were evaluated and DECLINED -- see the Phase 8 report.
    equal,
    not_equal,
    less,
    less_equal,
    greater,
    greater_equal,
    hypot,
    alltrue,
    sometrue,
    count_masked,
    allequal,
    amax,
    amin,
    argmax,
    argmin,
    cumsum,
    cumprod,
    ptp,
)

__all__ = [
    "count",
    "sum",
    "any",
    "all",
    "min",
    "max",
    "MaskedArray",
    "MaskedConstant",
    "nomask",
    "masked",
    "masked_singleton",
    "getdata",
    "getmask",
    "getmaskarray",
    "filled",
    "abs",
    "absolute",
    "fabs",
    "exp",
    "sin",
    "sinh",
    "cosh",
    "arctan",
    "arcsinh",
    "negative",
    "conjugate",
    "ceil",
    "floor",
    "logical_not",
    "add",
    "subtract",
    "multiply",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "arctan2",
    "logical_and",
    "logical_or",
    "logical_xor",
    "zeros_like",
    "ones_like",
    "empty_like",
    "zeros",
    "ones",
    "empty",
    "identity",
    "repeat",
    "take",
    "copy",
    "size",
    "ndim",
    "shape",
    "MaskType",
    "bool_",
    "MAError",
    "MaskError",
    "is_mask",
    "is_masked",
    "isMaskedArray",
    "isMA",
    "isarray",
    "make_mask",
    "make_mask_none",
    "mask_or",
    "masked_where",
    "masked_equal",
    "masked_not_equal",
    "masked_greater",
    "masked_greater_equal",
    "masked_less",
    "masked_less_equal",
    "masked_inside",
    "masked_outside",
    "masked_invalid",
    "masked_values",
    "masked_object",
    "masked_array",
    "masked_all",
    "masked_all_like",
    "masked_print_option",
    "default_fill_value",
    "minimum_fill_value",
    "maximum_fill_value",
    "common_fill_value",
    "set_fill_value",
    "fix_invalid",
    "vstack",
    "hstack",
    "dstack",
    "column_stack",
    "row_stack",
    "append",
    "diagflat",
    "transpose",
    "swapaxes",
    "reshape",
    "ravel",
    "squeeze",
    "expand_dims",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "resize",
    "compress",
    "compressed",
    "nonzero",
    "sqrt",
    "log",
    "log2",
    "log10",
    "arcsin",
    "arccos",
    "arccosh",
    "arctanh",
    "divide",
    "true_divide",
    "floor_divide",
    "remainder",
    "mod",
    "fmod",
    "equal",
    "not_equal",
    "less",
    "less_equal",
    "greater",
    "greater_equal",
    "hypot",
    "alltrue",
    "sometrue",
    "count_masked",
    "allequal",
    "amax",
    "amin",
    "argmax",
    "argmin",
    "cumsum",
    "cumprod",
    "ptp",
]
